apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: wp
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: wp.example.com
    http:
      paths:
      - path: /
        backend:
          serviceName: wp
          servicePort: 80
status:
  loadBalancer: {}
