apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: monitoring-grafana
  namespace: kube-system
spec:
  rules:
  - host: graphs.kubecluster.ouvrard.it
    http:
      paths:
      - backend:
          serviceName: monitoring-grafana
          servicePort: 80
