apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kibana-logging
  namespace: kube-system
  annotations:
    traefik.backend.loadbalancer.method: drr
    traefik.frontend.passHostHeader: "true"
    traefik.frontend.rule.type: PathPrefix
spec:
  rules:
  - host: kibana.example.com
    http:
      paths:
      - backend:
          serviceName: kibana-logging
          servicePort: 5601
